# Copyright 2008 Wincent Colaiuta
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

require 'rake'
require 'rake/clean'
require 'rubygems'
require 'spec/rake/spectask'

CLEAN.include   Rake::FileList['*.so', '*.bundle', '*.o', 'mkmf.log', 'Makefile']
CLOBBER.include Rake::FileList['wikitext_ragel.c']

task :default => :all

desc 'Build all and run all specs'
task :all => [:make, :spec]

extension_makefile  = 'Makefile'
ragel               = 'wikitext_ragel.c'
built_extension     = "wikitext.#{Config::CONFIG['DLEXT']}" # wikitext.bundle (Darwin), wikitext.so (Linux)
extension_files     = FileList[
  'Makefile',
  'wikitext.c',
  'wikitext.h',
  'wikitext_ragel.c',
  'wikitext_ragel.h',
]

desc 'Build C extension'
task :make => [ragel, extension_makefile, built_extension]

file ragel => ['wikitext_ragel.rl'] do
  # pass the -s switch here because otherwise Ragel is totally silent
  # I like to have visual confirmation that it's actually run
  sh 'ragel -s wikitext_ragel.rl'
end

file extension_makefile => ['extconf.rb', 'depend'] do
  if RUBY_PLATFORM =~ /darwin/
    sh "env ARCHFLAGS='-arch i386' ruby extconf.rb"
  else
    ruby 'extconf.rb'
  end
end

file built_extension => extension_files do
  sh 'make && touch .built'
end

desc 'Run specs'
Spec::Rake::SpecTask.new('spec') do |t|
  t.spec_files  = FileList['spec/**/*_spec.rb']
  t.spec_opts   = ['--color']
end
